// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnolptsgmaigpbbfgilm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhub2xwdHNnbWFpZ3BiYmZnaWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzQ1NzIsImV4cCI6MjA3NDY1MDU3Mn0.0d2k_qwO5jpK_RdiprOqTxc3DK4RGzp_InlqtQw4XI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});